name: 🚀 Feature Request
description: You have a specific idea to suggest for this project 💡
title: "💡 feat: <title>"
labels: enhancement
projects: ['Awesome-playwright-tests']
assignees:
  - idembele70
body:

  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to suggest a new feature!**

        Before you open an issue, please check if a similar issue already exists or has been closed before

  - type: textarea
    attributes:
      label: Actual Behavior
      description: Tell us what happened instead. Provide a screenshot if relevant.
      placeholder: "By going to the page '...' and pressing the button '...' then '...' happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Tell us what should happen.
      placeholder: "I expected by going to the page '...' and pressing the button '...' then '...' would happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false